# Algorithms before feature selection

In [150]:
## Import the required libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import os
import imblearn
from imblearn.pipeline import make_pipeline as make_pipeline_imbfinal 
from imblearn.over_sampling import SMOTE
from imblearn.metrics import classification_report_imbalanced
from sklearn.metrics import precision_score, recall_score, f1_score, roc_auc_score, accuracy_score, classification_report
from sklearn.cross_validation import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import BernoulliNB 
#from sklearn import svm
from sklearn.metrics import *
import zipfile
from zipfile import ZipFile
from io import BytesIO
import sys
import glob
import datetime
import time
import boto.s3
from boto.s3.key import Key 
import pickle
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

In [151]:
df = pd.read_csv('liver1.csv')

df.head()

id  age  tot_bilirubin  direct_bilirubin  tot_proteins  albumin  ag_ratio  \
0   1   65            0.7               0.1           187       16        18   
1   2   62           10.9               5.5           699       64       100   
2   3   62            7.3               4.1           490       60        68   
3   4   58            1.0               0.4           182       14        20   
4   5   72            3.9               2.0           195       27        59   

   sgpt  sgot  alkphos  gender_Male  is_patient  
0   6.8   3.3     0.90            0           0  
1   7.5   3.2     0.74            1           0  
2   7.0   3.3     0.89            1           0  
3   6.8   3.4     1.00            1           0  
4   7.3   2.4     0.40            1           0

In [152]:
col_list=['age','tot_bilirubin','direct_bilirubin','tot_proteins','albumin','ag_ratio','sgpt','sgot','alkphos'
          ,'gender_Male']
df_train,df_test = train_test_split(df,train_size=0.7,random_state=42)
x_train=df_train[col_list]
y_train=df_train['is_patient']
scaler.fit(x_train)
x_train_sc=scaler.transform(x_train)
x_test=df_test[col_list]
y_test=df_test['is_patient']
scaler.fit(x_test)
x_test_sc=scaler.transform(x_test)
print(x_train.shape,y_train.shape)

(338, 10) (338,)


In [153]:
accuracy =[]
model_name =[]
dataset=[]
f1score = []
precision = []
recall = []
true_positive =[]
false_positive =[]
true_negative =[]
false_negative =[]

# Logistic Regression

In [154]:
logreg = LogisticRegression()
## fitiing the model
logreg.fit(x_train_sc, y_train)
filename = 'logReg_model.sav'
pickle.dump(logreg,open(filename,'wb'))
logreg

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=None, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

Training

In [155]:
prediction = logreg.predict(x_train_sc)
f1 = f1_score(y_train, prediction)
p = precision_score(y_train, prediction)
r = recall_score(y_train, prediction)
a = accuracy_score(y_train, prediction)
cm = confusion_matrix(y_train, prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
dataset.append('Training')
model_name.append('Logistic Regression')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[ 43,  54],
       [  8, 233]], dtype=int64)

Testing

In [156]:
prediction = logreg.predict(x_test_sc)
f1 = f1_score(y_test,  prediction)
p = precision_score(y_test,  prediction)
r = recall_score(y_test,  prediction)
a = accuracy_score(y_test,  prediction)
cm = confusion_matrix(y_test,  prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Logistc Regression')
dataset.append('Testing')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[21, 32],
       [ 0, 93]], dtype=int64)

#  Bernoulli Naive Bayes

In [157]:
NB = BernoulliNB()
## fitiing the model
NB.fit(x_train_sc, y_train)
filename = 'BernoulliNB_model.sav'
pickle.dump(NB,open(filename,'wb'))
NB

BernoulliNB(alpha=1.0, binarize=0.0, class_prior=None, fit_prior=True)

Training

In [158]:
prediction = NB.predict(x_train_sc)
f1 = f1_score(y_train, prediction)
p = precision_score(y_train, prediction)
r = recall_score(y_train, prediction)
a = accuracy_score(y_train, prediction)
cm = confusion_matrix(y_train, prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Bernoulli Naive Bayes')
dataset.append('Training')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[ 59,  38],
       [ 21, 220]], dtype=int64)

Testing

In [159]:
prediction = NB.predict(x_test_sc)
f1 = f1_score(y_test,  prediction)
p = precision_score(y_test,  prediction)
r = recall_score(y_test,  prediction)
a = accuracy_score(y_test,  prediction)
cm = confusion_matrix(y_test,  prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Bernoulli Naive Bayes')
dataset.append('Testing')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[28, 25],
       [ 5, 88]], dtype=int64)

# Random Forest Classifier

In [160]:
rfc = RandomForestClassifier(n_estimators=50,random_state=0)
## fitiing the model
rfc.fit(x_train_sc, y_train)
filename = 'RFC_model.sav'
pickle.dump(rfc,open(filename,'wb'))
rfc

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=50, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

Training

In [161]:
prediction = rfc.predict(x_train_sc)
f1 = f1_score(y_train, prediction)
p = precision_score(y_train, prediction)
r = recall_score(y_train, prediction)
a = accuracy_score(y_train, prediction)
cm = confusion_matrix(y_train, prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Random Forest Classifier')
dataset.append('Training')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[ 97,   0],
       [  0, 241]], dtype=int64)

Testing

In [162]:
prediction = rfc.predict(x_test_sc)
f1 = f1_score(y_test,  prediction)
p = precision_score(y_test,  prediction)
r = recall_score(y_test,  prediction)
a = accuracy_score(y_test,  prediction)
cm = confusion_matrix(y_test,  prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Random Forest Classifier')
dataset.append('Testing')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[30, 23],
       [ 3, 90]], dtype=int64)

# k Nearest Neighbour

In [163]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 3)
knn.fit(x_train_sc, y_train)
filename = 'KNN_model.sav'
pickle.dump(knn,open(filename,'wb'))
knn

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=3, p=2,
           weights='uniform')

Training

In [164]:
prediction = knn.predict(x_train_sc)
f1 = f1_score(y_train, prediction)
p = precision_score(y_train, prediction)
r = recall_score(y_train, prediction)
a = accuracy_score(y_train, prediction)
cm = confusion_matrix(y_train, prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('k nearest Neighbour')
dataset.append('Training')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[ 63,  34],
       [  3, 238]], dtype=int64)

Testing

In [165]:
prediction = knn.predict(x_test_sc)
f1 = f1_score(y_test,  prediction)
p = precision_score(y_test,  prediction)
r = recall_score(y_test,  prediction)
a = accuracy_score(y_test,  prediction)
cm = confusion_matrix(y_test,  prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('k nearest Neighbour')
dataset.append('Testing')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[21, 32],
       [ 2, 91]], dtype=int64)

# Support Vector Classifier

In [166]:
from sklearn.svm import SVC
svc = SVC (kernel = 'linear' , C = 0.025 , random_state = 42)
svc.fit(x_train_sc, y_train)
filename = 'SVC_model.sav'
pickle.dump(svc,open(filename,'wb'))
svc

SVC(C=0.025, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='linear',
  max_iter=-1, probability=False, random_state=42, shrinking=True,
  tol=0.001, verbose=False)

Training

In [167]:
prediction = svc.predict(x_train_sc)
f1 = f1_score(y_train, prediction)
p = precision_score(y_train, prediction)
r = recall_score(y_train, prediction)
a = accuracy_score(y_train, prediction)
cm = confusion_matrix(y_train, prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Support Vector Classifier')
dataset.append('Training')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[ 30,  67],
       [  6, 235]], dtype=int64)

Testing

In [168]:
prediction = svc.predict(x_test_sc)
f1 = f1_score(y_test,  prediction)
p = precision_score(y_test,  prediction)
r = recall_score(y_test,  prediction)
a = accuracy_score(y_test,  prediction)
cm = confusion_matrix(y_test,  prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Support Vector Classifier')
dataset.append('Testing')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[16, 37],
       [ 0, 93]], dtype=int64)

# Stochastic Gradient Decent

In [169]:
from sklearn.linear_model import SGDClassifier
sgd = SGDClassifier (loss = 'modified_huber' , shuffle = True , random_state = 42)
sgd.fit(x_train_sc, y_train)
filename = 'SGD_model.sav'
pickle.dump(sgd,open(filename,'wb'))
sgd

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\stochastic_gradient.py:128: FutureWarning: max_iter and tol parameters have been added in <class 'sklearn.linear_model.stochastic_gradient.SGDClassifier'> in 0.19. If both are left unset, they default to max_iter=5 and tol=None. If tol is not None, max_iter defaults to max_iter=1000. From 0.21, default max_iter will be 1000, and default tol will be 1e-3.
  "and default tol will be 1e-3." % type(self), FutureWarning)


SGDClassifier(alpha=0.0001, average=False, class_weight=None, epsilon=0.1,
       eta0=0.0, fit_intercept=True, l1_ratio=0.15,
       learning_rate='optimal', loss='modified_huber', max_iter=None,
       n_iter=None, n_jobs=1, penalty='l2', power_t=0.5, random_state=42,
       shuffle=True, tol=None, verbose=0, warm_start=False)

Training

In [170]:
prediction = sgd.predict(x_train_sc)
f1 = f1_score(y_train, prediction)
p = precision_score(y_train, prediction)
r = recall_score(y_train, prediction)
a = accuracy_score(y_train, prediction)
cm = confusion_matrix(y_train, prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Stochastic Gradient Decent')
dataset.append('Training')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[ 50,  47],
       [ 15, 226]], dtype=int64)

Testing

In [171]:
prediction = sgd.predict(x_test_sc)
f1 = f1_score(y_test,  prediction)
p = precision_score(y_test,  prediction)
r = recall_score(y_test,  prediction)
a = accuracy_score(y_test,  prediction)
cm = confusion_matrix(y_test,  prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Stochastic Gradient Decent')
dataset.append('Testing')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[23, 30],
       [ 3, 90]], dtype=int64)

# Gradient Naive Bayes

In [172]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train_sc, y_train)
filename = 'GNB_model.sav'
pickle.dump(gnb,open(filename,'wb'))
gnb

GaussianNB(priors=None)

Training

In [173]:
prediction = gnb.predict(x_train_sc)
f1 = f1_score(y_train, prediction)
p = precision_score(y_train, prediction)
r = recall_score(y_train, prediction)
a = accuracy_score(y_train, prediction)
cm = confusion_matrix(y_train, prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Gradient Naive Bayes')
dataset.append('Training')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[ 40,  57],
       [ 10, 231]], dtype=int64)

Testing

In [174]:
prediction = gnb.predict(x_test_sc)
f1 = f1_score(y_test,  prediction)
p = precision_score(y_test,  prediction)
r = recall_score(y_test,  prediction)
a = accuracy_score(y_test,  prediction)
cm = confusion_matrix(y_test,  prediction)
tp = cm[0][0]
fp = cm[0][1]
fn = cm[1][0]
tn = cm[1][1]
model_name.append('Gradient Naive Bayes')
dataset.append('Testing')
f1score.append(f1)
precision.append(p)
recall.append(r)
accuracy.append(a)
true_positive.append(tp) 
false_positive.append(fp)
true_negative.append(tn) 
false_negative.append(fn)
cm

array([[21, 32],
       [ 2, 91]], dtype=int64)

# Writing summary metrics

In [175]:
Summary = model_name,dataset,f1score,precision,recall,accuracy,true_positive,false_positive,true_negative,false_negative
#Summary

In [176]:
## Making a dataframe of the accuracy and error metrics
describe1 = pd.DataFrame(Summary[0],columns = {"Model_Name             "})
describe2 = pd.DataFrame(Summary[1],columns = {"Dataset"})
describe3 = pd.DataFrame(Summary[2],columns = {"F1_score"})
describe4 = pd.DataFrame(Summary[3],columns = {"Precision_score"})
describe5 = pd.DataFrame(Summary[4],columns = {"Recall_score"})
describe6 = pd.DataFrame(Summary[5], columns ={"Accuracy_score"})
describe7 = pd.DataFrame(Summary[6], columns ={"True_Positive"})
describe8 = pd.DataFrame(Summary[7], columns ={"False_Positive"})
describe9 = pd.DataFrame(Summary[8], columns ={"True_Negative"})
describe10 = pd.DataFrame(Summary[9], columns ={"False_Negative"})
des = describe1.merge(describe2, left_index=True, right_index=True, how='inner')
des = des.merge(describe3,left_index=True, right_index=True, how='inner')
des = des.merge(describe4,left_index=True, right_index=True, how='inner')
des = des.merge(describe5,left_index=True, right_index=True, how='inner')
des = des.merge(describe6,left_index=True, right_index=True, how='inner')
des = des.merge(describe7,left_index=True, right_index=True, how='inner')
des = des.merge(describe8,left_index=True, right_index=True, how='inner')
des = des.merge(describe9,left_index=True, right_index=True, how='inner')
des = des.merge(describe10,left_index=True, right_index=True, how='inner')
#des = des.merge(describe9,left_index=True, right_index=True, how='inner')
#Summary_csv = des.sort_values(ascending=True,by="False_Negative").reset_index(drop = True)
des

Model_Name                Dataset  F1_score  Precision_score  \
0          Logistic Regression  Training  0.882576         0.811847   
1           Logistc Regression   Testing  0.853211         0.744000   
2        Bernoulli Naive Bayes  Training  0.881764         0.852713   
3        Bernoulli Naive Bayes   Testing  0.854369         0.778761   
4     Random Forest Classifier  Training  1.000000         1.000000   
5     Random Forest Classifier   Testing  0.873786         0.796460   
6          k nearest Neighbour  Training  0.927875         0.875000   
7          k nearest Neighbour   Testing  0.842593         0.739837   
8    Support Vector Classifier  Training  0.865562         0.778146   
9    Support Vector Classifier   Testing  0.834081         0.715385   
10  Stochastic Gradient Decent  Training  0.879377         0.827839   
11  Stochastic Gradient Decent   Testing  0.845070         0.750000   
12        Gradient Naive Bayes  Training  0.873346         0.802083   
13        Gradient Naive Bayes   Testing  0.842593         0.739837   

    Recall_score  Accuracy_score  True_Positive  False_Positive  \
0       0.966805        0.816568             43              54   
1       1.000000        0.780822             21              32   
2       0.912863        0.825444             59              38   
3       0.946237        0.794521             28              25   
4       1.000000        1.000000             97               0   
5       0.967742        0.821918             30              23   
6       0.987552        0.890533             63              34   
7       0.978495        0.767123             21              32   
8       0.975104        0.784024             30              67   
9       1.000000        0.746575             16              37   
10      0.937759        0.816568             50              47   
11      0.967742        0.773973             23              30   
12      0.958506        0.801775             40              57   
13      0.978495        0.767123             21              32   

    True_Negative  False_Negative  
0             233               8  
1              93               0  
2             220              21  
3              88               5  
4             241               0  
5              90               3  
6             238               3  
7              91               2  
8             235               6  
9              93               0  
10            226              15  
11             90               3  
12            231              10  
13             91               2

In [177]:
Summary_csv.to_csv('Summary.csv')

Conclusion: We are getting 100% accuracy for `Random Forest Classifier` and for every other model, we have some error which we have to rectify.